### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by TypzVR** [Jamalam360/ExcessEnchantments#3]
It says that it failed to load Minecraft. It says: 

Could not find required mod: excessenchantmentsfabric requires {fabricloader @ [>=0.11.3]}
Creating Empty clause ?
 

Pls help, cuz this mod looks SICK

**Comment by K0-RR** [comment]
Update your Fabric Loader as stated in this message.

**Comment by K0-RR** [comment]
I recommend using MultiMC because there you can do it in a few seconds, without downloading installer from the website.

**Comment by TypzVR** [comment]
> Update your Fabric Loader as stated in this message.

Absolute Legend! Thank you!

**Comment by Jamalam360** [comment]
Thank you @RDKRACZ
